### PR TITLE
update location method name that was changed in stanford mods

### PR DESCRIPTION
**Pull request by peetucket**
update to version 1.0 of base_indexer so we can get latest stanford mods gem

### CODE REVIEW

**Comment by peetucket** [comment]
made the necessary changes, but tests are failing for unknown reason --- i see them failing too in the update_dependencies branch so I think it is something upstream that changed...punting on dealing with this for now, but this change needs to make it into master when work on this resumes

**Comment by jkeck** [comment]
FWIW, the failure looks like it's in the build itself.  It's trying to run `rake db:migrate` but no `schema.rb` exists.

---

/home/travis/build/sul-dlss/spotlight-indexer-service/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /home/travis/build/sul-dlss/spotlight-indexer-service/config/application.rb to limit the frameworks that will be loaded.

---

**Comment by peetucket** [comment]
huh, I'm seeing this failure (and travis is too):

spotlight-indexer-service/lib/spotlight_mapper.rb:1:in `<top (required)>': uninitialized constant DiscoveryIndexer::Mapper (NameError)
    from /Users/petucket/Sites/development/spotlight-indexer-service/spec/spotlight_mapper_spec.rb:3:in`<top (required)>'

like there was a change in class name or namespace

**Comment by peetucket** [comment]
The test failures were due to a non-backwards compatible change in discovery-indexer committed in mid-December.  I started to make the changes on this branch, and believe I made the necessary code changes ,but the tests are still broken and need to be sorted out.  Basically, the setup is now quite different for the tests.  See this commit in sw-indexer-service for an example: https://github.com/sul-dlss/sw-indexer-service/commit/6fc0c0e984687f51eebd785fe34d35b4ce2b320e

**Comment by peetucket** [comment]
no longer necessary

**Pull request closed without merging**
